spring:
  application:
    name: service-turbine
server:
  port: 8770

turbine:
  aggregator:
  #可以不写 默认就是default
    clusterConfig:  default
#    需要监控的服务名
  app-config:  eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

